### ISSUE TITLE
Banner background cover not working

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/ecommerce-pattern-library#2]
Hi Thomas,
I am trying to make my image for my banner have a dark cover so you can see the text better but it isn't working.

@thomasjbradley
<img width="1124" alt="Screen Shot 2020-02-02 at 1 23 59 PM" src="https://user-images.githubusercontent.com/43240727/73613124-82e05a00-45c0-11ea-9834-d957be37e24a.png">
<img width="1392" alt="Screen Shot 2020-02-02 at 1 32 21 PM" src="https://user-images.githubusercontent.com/43240727/73613125-8378f080-45c0-11ea-8413-8a78d9a90ecc.png">
<img width="760" alt="Screen Shot 2020-02-02 at 1 32 31 PM" src="https://user-images.githubusercontent.com/43240727/73613126-8378f080-45c0-11ea-8dbf-7f95717be10e.png">
<img width="802" alt="Screen Shot 2020-02-02 at 1 32 37 PM" src="https://user-images.githubusercontent.com/43240727/73613127-8378f080-45c0-11ea-8376-ddb8580d5d83.png">

**Comment by thomasjbradley** [comment]
Instead of using a gradient you could set the background colour to black and use `opacity` to make the image partially see-through to the black itself.

**Comment by fuen0015** [comment]
That worked thank you :)
