### ISSUE TITLE
Product-page not working

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/ecommerce-pattern-library#3]
Hello Thomas,
My Product page is not working, the config.yml is not connecting with the html

<img width="628" alt="Screen Shot 2020-03-09 at 7 37 20 PM" src="https://user-images.githubusercontent.com/43240727/76266333-71ccdd80-623d-11ea-834f-177ed5c4b353.png">
<img width="428" alt="Screen Shot 2020-03-09 at 7 37 27 PM" src="https://user-images.githubusercontent.com/43240727/76266335-72657400-623d-11ea-905c-7915d27fc157.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
Have you committed this stuff? I don’t see it in the code.
