### ISSUE TITLE
Preparing Product Data Not Working Week 10

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/ecommerce-pattern-library#4]
Hello Thomas,
I do not know how to get to the next step for this
<img width="1680" alt="Screen Shot 2020-03-22 at 1 49 59 PM (2)" src="https://user-images.githubusercontent.com/43240727/77256943-ad0cda80-6c47-11ea-9b79-5abe41f5a440.png">
I don't see my product page at all
@thomasjbradley

**Comment by thomasjbradley** [comment]
The `products.html` file in the root folder should be moved into `_layouts` and renamed to `product.html` (no “s”).

**Comment by fuen0015** [comment]
I am almost at the end but my products are not showing on separate pages and my footer is being effected
<img width="1680" alt="Screen Shot 2020-03-23 at 8 53 58 PM" src="https://user-images.githubusercontent.com/43240727/77377071-7bc80380-6d48-11ea-9128-46ce518b6cb7.png">
<img width="559" alt="Screen Shot 2020-03-23 at 8 54 08 PM" src="https://user-images.githubusercontent.com/43240727/77377076-7f5b8a80-6d48-11ea-8459-e19f524c8ccc.png">
