### ISSUE TITLE
Grades For eCommerce UX inspiration

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/ecommerce-pattern-library#6]
I did this in class but I did not get marked
<img width="507" alt="Screen Shot 2020-03-23 at 6 40 19 PM" src="https://user-images.githubusercontent.com/43240727/77438520-4eb53880-6dbc-11ea-9d3e-9405b8ee1e2c.png">
<img width="796" alt="Screen Shot 2020-03-23 at 6 40 27 PM" src="https://user-images.githubusercontent.com/43240727/77438523-4f4dcf00-6dbc-11ea-9412-323e5c8a6cb0.png">
@thomasjbradley

**Comment by thomasjbradley** [comment]
Okay…
